### ISSUE TITLE
Not sure, what HA_MQTT_ADDRESS is

### ISSUE THREAD

**Issue by silelmot** [AnotherDaniel/smahub#15]
Hi, 
I was really glad to see your work as I struggle with my sm energy meter to get data from. 
I installed. Smahub via docker compose but am unsure how HA_MQTT_ADDRESS=192.168.0.3 works.
Adding the op of my ha seems wrong. I don't get any data. Do I need a broker still?

If ma_mqtt fails, is there a template to integrate data via a mqtt-broker?

Vielen Dank im Voraus

**Comment by silelmot** [comment]
Edit: is a problem in class container, without it works well

**Comment by AnotherDaniel** [comment]
Hi @silelmot, yes HA_MQTT_ADDRESS is the address of the mqtt broker that you're using with home assistant - smahub does not bring it's own broker, it just publishes data to the one behind HA_MQTT_ADDRESS.

Can you re-state your question, if there still is one? I'd like to help you get going, if there still is a snag.

**Comment by silelmot** [comment]
Got it working now. Had debian 10 running on my server. After Upgrading it works fine for now (I still have no password for my smd but with your script I get some useful info's at least)

**Comment by AnotherDaniel** [comment]
Ok that's good to hear!
