### ISSUE TITLE
Reported power usage does not match SunnyPortal values

### ISSUE THREAD

**Issue by devfaz** [AnotherDaniel/smahub#24]
Hi,

just upgraded to the latest 1.5.2 (is there no 1.4.x?) and it seems the reported power_usage is no longer matching with  the values reported by sunnyPortal.

Last version working as expected is 1.3.2 - maybe related to the INTERVAL-fixes?

to reproduce:

* setup MQTT sink (without HA - if important)
* setup SMA source
* open sunnyPortal
* keep an eye on both values
* power on a new device to enforce a value change
* wait...
* sunnyPortal will report new power requirements within seconds
* SMAHUB will continue to report the old values, just slightly changing over time.

**Comment by AnotherDaniel** [comment]
Hi @devfaz , thank you for the report! I will have a look at this - with "SMA Source", you're referring to the SHM2 plugin, correct?

**Comment by devfaz** [comment]
> Hi @devfaz , thank you for the report! I will have a look at this - with "SMA Source", you're referring to the SHM2 plugin, correct?

Correct 💯😁

**Comment by devfaz** [comment]
@AnotherDaniel attached PR fixes the issue. Was caused by old (not read) data in the socket.

**Comment by AnotherDaniel** [comment]
Looking good, thank you for this!

**Comment by devfaz** [comment]
Well, it's a k3s system nothing special. Intel i5 (don't ask which :) ) - 16G memory in my basement. The average load is 1 - why?

**Comment by AnotherDaniel** [comment]
Just wondering whether system resources/load plays a role in getting this issue reproducible. I had a look on my dev machine with no luck, that's why I'm asking :-)

**Comment by devfaz** [comment]
Hmm ok, I'm getting SHM broadcasts every second and since 1.5.x these are only read every 2s, so filling up over time.

Don't know what triggers these broadcasts? Maybe my usage changes more often?
