### ISSUE TITLE
Home Assistant Port Settings

### ISSUE THREAD

**Issue by ennosun** [AnotherDaniel/smahub#49]
Hey AnotherDaniel,

it is maybe possible, that you integrate a port settings like HA_MQTT_PORT for the HA_MQTT sink? 

In ha_mqtt.py I think it would be:
    if os.environ.get('HA_MQTT_PORT'):
        config['server']['port'] = os.environ.get('HA_MQTT_PORT')
But I dont know how to handle the opening for this:
    mqtt_settings = Settings.MQTT(host=config['server']['address'],
                                  username=config['server']['username'],
                                  password=config['server']['password'],
                                  discovery_prefix=config['behavior']['sensorprefix'])

Greetings

Henning

**Comment by AnotherDaniel** [comment]
Hi Henning, thank you for taking the time to write this proposal. Unfortunately, smahub is using the [ha-mqtt-discoverable](https://github.com/unixorn/ha-mqtt-discoverable) library for the ha_mqtt plugin, and that doesn't offer the option to change mqtt server ports.

(unless I'm blind and just didn't see it, in which case I'd be happy to be corrected on this)
